codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        base: auto
        flags:
          - unit
        paths:
          - ^packages.*
        target: 80%
        threshold: 5%
    patch:
      default:
        base: auto
        flags:
          - unit
        paths:
          - ^packages.*
        target: auto
        threshold: 5%


parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  behavior: default
  layout: "reach,diff,flags,tree"
  require_changes: false
